config/routes.rb
FoodCorp::Application.routes.draw do

  get "locations/new"

  resources :comments
	
  resources :meal_arrangements
   
  resources :ratings
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
                                       :registrations => "registrations" }

  resources :users do
    resources :locations
    match 'info' => :info
  end

  resources :fellowships
  
  resources :meals
    match 'recipes' => 'Meals#recipes', :as => 'recipes'
    match 'own_dated_meal' => 'Meals#own_dated_meal', :as => 'dates'
    match 'meals/:id/:status' => 'Meals#show', :as => 'meal_arrangement_status'
    match 'meals/create_comment' => 'Meals#create_comment', :as => 'create_commit'
  
  controller :meals do
  end

  controller :messages do
    match 'messages/in' => :inbox
    match 'messages/out' => :outbox
  end
  resources :messages

  controller :pages do
     match 'about' => :about
     match 'imprint' => :imprint
     match 'terms' => :terms
     match 'tour' => :tour
  end

  controller :ajax do
     match 'ajax/calendar' => :calendar
     match 'ajax/updatemap' => :update_map
     match 'ajax/following' => :following
     match 'ajax/followed' => :followed
  end

  root :to => "meals#index"

end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :receiver, :topic, :body
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_filter :check_login, :only=> [:inbox, :new, :create]
  before_filter :check_receiver, :only=> [:new, :create]

  def index
    redirect_to :action => "inbox"
  end

  def inbox
    @messages = current_user.received
    render :index
  end

  def outbox
    @messages = current_user.sent
    render :index
  end

  def show
    @msg = Message.find(params[:id])
    if @msg.received_messageable_id == current_user.id
      @msg.update_attribute(:opened, true)
    else
      unless @msg.sent_messageable_id == current_user.id
        redirect_to root_path, :notice => I18n.t('application.rights_fail')
      end
    end
  end

  def new
    @new_message = Message.new
  end

  def create
    current_user.send_message(@receiver, params[:topic], params[:body])
    MealMailer.notification_email(current_user, @receiver, params[:body]).deliver if @receiver.mail_notification
    redirect_to user_path(@receiver.id)
  end

  protected
  def check_login
    unless current_user
      flash[:alert] = I18n.t('application.access_denied')
      redirect_to root_path
    end
  end

  def check_receiver
    unless @receiver = User.find(:first, :conditions => [ "id = ?", params[:receiver]])
      flash[:alert] = I18n.t('application.no_such_user')
      redirect_to root_path
    end
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
  def get_username_by_id(id)
    user = User.find(id)
    return user.first_name + " " + user.last_name
  end
end

app/views/messages/index.html.erb
<div id="main_header">
  <h3>Your Messages</h3>
  <div id="tabnav">
    <ul>
      <li><%= link_to I18n.t('tab.inbox'), messages_in_path, :class => is_active?("inbox") %> </li>
      <li><%= link_to I18n.t('tab.outbox'), messages_out_path, :class => is_active?("outbox") %> </li>
    </ul>
  </div>
</div>

<div id="main_body">
  <ul>
  <% @messages.each do |msg| %>
    <li>
      <% if msg.opened %>
        <%= image_tag("mail_mark_read_icon.png") %>
      <% else %>
        <%= image_tag("mail_mark_unread_icon.png") %>
      <% end %>
      <%= link_to msg.topic, message_path(msg.id)  %>
      <% if params[:action] == "inbox" %>
        <%= link_to get_username_by_id(msg.sent_messageable_id), user_path(msg.sent_messageable_id), :class => "float_right" %>
      <% else %>
        <%= link_to get_username_by_id(msg.received_messageable_id), user_path(msg.received_messageable_id), :class => "float_right" %>
      <% end  %>
    </li>
  <% end %>
  </ul>
</div>

app/views/messages/new.html.erb
<div id="main_header">
  <h3>New Message to <%= @receiver.first_name %> <%= @receiver.last_name %></h3>
</div>
<div id="main_body">
  <%= form_tag(messages_path) do %>
    <p><%= label_tag :receiver %></p>
    <p><%= @receiver.first_name %> <%= @receiver.last_name %></p><br/>
    <p><%= label_tag :topic %></p>
    <p><%= text_field_tag :topic %></p>
    <p><%= label_tag :body %></p>
    <p><%= text_area_tag :body, nil, :rows => 10, :cols => 40 %></p>
    <%= hidden_field_tag(:receiver, @receiver.id) %>
    <%= submit_tag 'submit', :class => "submit" %>
  <% end %>
</div>

<div>
<div class="tab_container">
  <div id="New" class="tab_content">
  </div>
</div>
</div>

<div class="clr"></div>

app/views/messages/show.html.erb
<div id="main_header">
  <h3>Your Messages</h3>
</div>

<div id="main_body">
<p><%= @msg.topic %></p>
<p><%= @msg.body %></p>

<%= link_to "Back", :back %>
</div>