config/routes.rb
FoodCorp::Application.routes.draw do

  get "locations/new"

  resources :comments
	
  resources :meal_arrangements
   
  resources :ratings
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
                                       :registrations => "registrations" }

  resources :users do
    resources :locations
    match 'info' => :info
  end

  resources :fellowships
  
  resources :meals
    match 'recipes' => 'Meals#recipes', :as => 'recipes'
    match 'own_dated_meal' => 'Meals#own_dated_meal', :as => 'dates'
    match 'meals/:id/:status' => 'Meals#show', :as => 'meal_arrangement_status'
    match 'meals/create_comment' => 'Meals#create_comment', :as => 'create_commit'
  
  controller :meals do
  end

  controller :messages do
    match 'messages/in' => :inbox
    match 'messages/out' => :outbox
  end
  resources :messages

  controller :pages do
     match 'about' => :about
     match 'imprint' => :imprint
     match 'terms' => :terms
     match 'tour' => :tour
  end

  controller :ajax do
     match 'ajax/calendar' => :calendar
     match 'ajax/updatemap' => :update_map
     match 'ajax/following' => :following
     match 'ajax/followed' => :followed
  end

  root :to => "meals#index"

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :meals
  has_many :meal_arrangements
  has_many :comments
  has_one :location
  has_many :rating
  
  # Followers
  has_many :fellowships
  has_many :followers, :through => :fellowships
  has_many :inverse_fellowships, :class_name => "Fellowship", :foreign_key => "follower_id"
  has_many :inverse_followers, :through => :inverse_fellowships, :source => :user

  has_attached_file :avatar, :styles => { :medium => "200x200>", :thumb => "50x50>" }

  acts_as_messageable

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :lockable, :timeoutable and
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,
                  :first_name, :last_name, :gender, :birthday, :fb_id, :avatar, :use_fb_avatar,
                  :country, :city, :zip_code, :street, :street_number, :phone_number, :info_field, 
                  :mail_notification, :got_invitation, :location_id, :meal_counter

  validates :first_name, :presence => true
  validates :last_name, :presence => true
  validates :gender, :presence => true
  
   
  

  def self.find_for_facebook_oauth(access_token, signed_in_resource=nil)
    data = access_token['extra']['user_hash']
    if user = User.find_by_email(data["email"])
      user.fb_id = data["id"]
      user.birthday = data["birthday"]

      if data["hometown"] # Insert hometown if available on
        hometown = data["hometown"]["name"].to_s.split(", ")
        user.country = hometown[2] if user.country.blank?
        user.city = hometown[0] if user.city.blank?
      end

      user.confirm!
      user.save
      user
    else # Create an user with a stub password and some data from fb.
      user = User.new(:email => data["email"],
                      :password => Devise.friendly_token[0,20],
                      :first_name => data["first_name"],
                      :last_name => data["last_name"],
                      :gender => data["gender"],
                      :birthday => data["birthday"],
                      :fb_id => data["id"],
                      :use_fb_avatar => true
                     )

      if data["hometown"] # Insert hometown if available on
        hometown = data["hometown"]["name"].to_s.split(", ")
        user.country = hometown[2]
        user.city = hometown[0]
      end

      user.confirm!
      user.save!
      user
    end
  end

  def password_required?
    new_record?
  end

  def is_meal_from_user?(meal_id)
    Meal.find(meal_id).user_id == self.id
  end

  def fb_user
    if fb_id
      true
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model
    @user = User.find_for_facebook_oauth(env["omniauth.auth"], current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.facebook_data"] = env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :get_user, :only=> [:show, :info]

  def index
    redirect_to root_path
  end

  def info
  end
 
  def show
    @meals = Meal.find(:all, :conditions => ["user_id = ?", params[:id]], :order => 'created_at DESC')
    @rating = Rating.find(:all)
  end
  
  def update 
    if params[:user_id] # wants to get mails?
      user = User.find(params[:user_id])
      if params[:user] && params[:user][:mail_notification] # in user's profile
        user.update_attributes(:mail_notification => params[:user][:mail_notification] ) 
      end
      
      if params[:receive_mail] # in show meal
        if params[:receive_mail] == '1'
		  user.update_attributes(:mail_notification => true ) 
        else
          user.update_attributes(:mail_notification => false ) 
        end
      end
      redirect_to :back, :notice => 'Mail Notifications updated'
    end
    
    if params['users'] # send invitation mail
      if params['users']['user_id'] 
        user_to_invite = User.find(params['users']['user_id'])
        
        if user_to_invite.mail_notification
          MealMailer.notification_email(current_user, user_to_invite, "Cook #{current_user.first_name.concat(' ')<<current_user.last_name} want to invite you").deliver
        end
        
        user_to_invite.update_attributes( :got_invitation => true )
        
        redirect_to user_path(current_user.id), :notice => I18n.t('user.invitaion_mail_success')
      else
        redirect_to user_path(current_user.id), :notice => I18n.t('user.invitaion_mail_fail')
      end
    end
  end
  
  protected
  def get_user
    if @user = User.find(:first, :conditions => [ "id = ? || id = ?", params[:id], params[:user_id]])
    else
      redirect_to root_path
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def get_following(args)
    return Fellowship.find(:first, :conditions => { :user_id => current_user.id, :follower_id => args[:user].id } )
  end

  def is_following(current_user, user)
    if (current_user && Fellowship.where(:user_id => current_user.id, :follower_id => user.id ).count > 0)
     return true
    else
      return false
    end
  end

  def get_user_name(args)
    return User.find(args)
  end

  def comment_admit(args)
    if MealArrangement.where("acceptance = 1 AND user_id = ? AND meal_id = ? ", current_user.id, args ).count > 0
      return true
    else
      return false
    end
  end

end

app/views/users/_mail_notifications_buttons.html.erb
<p>Mail Notifictions are 
  <% if on %>
	<b>on</b>
  <% else %>
	<b>off</b>
  <% end %>
</p>

<p>
  <%= label_tag "yes:" %>
  <%= radio_button_tag 'receive_mail', '1', true %>
</p>
<p>
  <%= label_tag "no thanks:" %>
  <%= radio_button_tag 'receive_mail', '0', false %>
</p>

app/views/users/_meal_arrangement_delete_form.html.erb
<%= form_tag(meal_arrangement_path(meal_arrangement.id), :method => "delete") do %>
  <%= image_submit_tag("delete_meal_request.png", :id => "delete_meal_request") %>
<%end%>

app/views/users/_meal_arrangement_requests.html.erb
<% if meal.meal_arrangements.count > 0 %>
<ul>
  <% meal.meal_arrangements.each do |meal_arrangement| %>
    <% if meal_arrangement.acceptance == false  && meal.slots > 0 %>
      <li><%= link_to meal_arrangement.user.first_name+" "+meal_arrangement.user.last_name, user_path(meal_arrangement.user_id) %>
     (<%= link_to "Accept", meal_arrangement_path( meal_arrangement.id), :method => 'put', :class => 'accept' %> /
      <%= link_to "Delete", meal_arrangement_path( meal_arrangement.id), :method => 'delete', :class => 'delete' %>)</li>
    <%end%>
  <%end%>
      </ul>
<%else%>
  <ul><li>none</li></ul>
<%end%>

app/views/users/_meal_arrangement_update_form.html.erb
<%= form_tag(meal_arrangement_path(meal_arrangement.id), :method => "put") do %>
  <%= image_submit_tag("accepted.png", :id => "delete_meal_request") %>
<%end%>

app/views/users/_meal_cook_guest_title.html.erb
<% if current_user %>
  <% if meal.user_id == current_user.id %>
	<h3>You are host of meal: <%= meal.title %></h3>
  <% else %>
	
	<% if meal_arrangement && meal_arrangement.user_id == current_user.id && meal_arrangement.acceptance %>
	  <h3>You are guest of meal: <%= meal.title %></h3>
	<% else %>
	  <% if meal_arrangement.nil? %>
		<% if current_user.points > 0 %>
			<h3>You are no guest of meal <%= meal.title %> yet, but you can order it.</h3>
		<% elsif current_user.points == 0 %>
			<h3>Sorry, you can not order meal <%= meal.title %>, because you have got no points.</h3>
		<% end %>
	  <% else %>
	    <h3>Your request is made, but you are not been accepted by the host yet.</h3>
	  <% end %>
	<% end %>
  
  <% end %>
  
<% else %>
  <h3>You are not logged in.</h3>
<% end %>

app/views/users/_meals_eat_in_take_away.erb
<% if meal.eat_in %>
	<b>Eat in</b>
<% end %>
<br />
<% if meal.take_away %>
	<b>Take away</b>
<% end %>

app/views/users/_meals_eat_in_take_away.html.erb
<% if meal.eat_in %>
	<b>Eat in</b>
<% end %>
<br />
<% if meal.take_away %>
	<b>Take away</b>
<% end %>

app/views/users/_provided_meals.html.erb
<% if meals.count < 1 %>
	<p> No meals yet! </p>
	<p> <%= link_to "New Meal", new_meal_path, :class => is_active?("new") %></p>
<% else %>
<div id="provided_meals">
 <h4>Current Invitations</h4>
  <% mdisplay = 0 %>
  <% meals.each do |meal|%>
	
	<%# time_to_check = meal.time + (meal.times.strftime("%H").to_i).hours - 3.hours + (meal.times.strftime("%M").to_i).minutes%>
    <% if meal.check_time > Time.now %>
		<% mdisplay = mdisplay+1 %>
    <div class="display_meal">
      <div class="meal_title"><%= link_to meal.title, meal_path(meal.id) %></div>

		<div class="meal_right">
			<img src="/images/closed.png" title="open" alt="open" class="openMeal" /><br>
			<img src="/images/compass.png" title="Map" alt="Location" class="hoverMap" />
			<div id="map"></div>
		</div>
		<div class="clear"></div>
		<span class="meal_info_right">		 
		 <% if meal.vegetarien %>
		   <%= image_tag getCategorieImageName(0), :alt => "veggie", :title => "veggie" %>
		 <% end %>
		 <% if meal.organic %>
		   <%= image_tag getCategorieImageName(1), :alt => "organic", :title => "organic" %>
		 <% end %>
		 <% if meal.kosher %>
		   <%= image_tag getCategorieImageName(2), :alt => "kosher", :title => "hosher" %>
		 <% end %>
		 <% if meal.asian %>
		   <%= image_tag getCategorieImageName(3), :alt => "asian", :title => "asian" %>
		 <% end %>
		 <% if meal.lactose_free %>
		   <%= image_tag getCategorieImageName(4), :alt => "lactose free", :title => "lactose free" %>
		 <% end %>
		 <% if meal.gluten_free %>
		   <%= image_tag getCategorieImageName(5), :alt => "gluten", :title => "gluten" %>
		 <% end %>
		 <% if meal.halal %>
		   <%= image_tag getCategorieImageName(6), :alt => "halal", :title => "halal" %>
		 <% end %>
		 <% if meal.hot %>
			<%= image_tag getCategorieImageName(7), :alt => "hot", :title => "hot" %>
		 <% end %>
		 <% if meal.veryhot %>
			<%= image_tag getCategorieImageName(8), :alt => "veryhot", :title => "veryhot" %>
		 <% end %>
		</span>
        <span class="float_right space_right space_bottom">
          
          <%= link_to image_tag("edit_meal.png", :title => "edit"), edit_meal_path(meal.id) if current_user && current_user.id == meal.user_id %>
        </span>
      
      
      <div class="meal_info"><%=l meal.time, :format => :short %> - <%=  meal.short_time %><br>
        <br /><br />
        <% if current_user %>
          <% if current_user.id == meal.user_id %>
			<div id="meal_info_right">
				<p><%= meal.slots %><b>Guests</b></p>
				<b>Apply until:</b><br />
				
				<%= l meal.deadline, :format => :short %> - <%= meal.short_deadline %>
				<br>Accepted Users:<br>
				<% if meal.meal_arrangements.count > 0 %>
				  <ul>
					<% meal.meal_arrangements.each do |mealArrangement| %>
					  <% if mealArrangement.acceptance %>
						<li><%= link_to mealArrangement.user.first_name+" "+mealArrangement.user.last_name, user_path(mealArrangement.user_id) %></li>
					  <% end %>
					<% end %>
				  </ul>
				<% else %>
				  <ul><li>none</li></ul>
				<% end %>
				<br>Outstanding Meal Requests<br>
				<%= render 'meal_arrangement_requests', :meal => meal %>
				<br />
				<% if meal.eat_in %>
					<b>Eat in</b>
				<% end %>
				<br />
				<% if meal.take_away %>
					<b>Take away</b>
				<% end %>
				
		    </div>

			<div id="meals_distance_stream" style="display:none">
				<div class="meal" id="meal_<%= meal.id %>">
					<input type="hidden" title="lat" value="<%= meal.lat %>" />
					<input type="hidden" title="lon" value="<%= meal.lon %>" />
				</div>
			</div>
      
      <%end%>
      <%end%>
      </div>
    </div>
   <% end %>
   <% end %>
   <% if mdisplay == 0 %>
     <h2>No current Meals!</h2>
   <% end %>
</div>

<div id="provided_meals">
 <h4>Formerly cooked</h4>
  <% mdisplay = 0 %>
  <% meals.each do |meal|%>
  <%# time_to_check = meal.time + (meal.times.strftime("%H").to_i).hours - 3.hours + (meal.times.strftime("%M").to_i).minutes%>
    <% if meal.check_time < Time.now %>
    <% mdisplay = mdisplay + 1 %>
    <div class="display_formerly_meal">
      <div class="formerly_meal_title"><%= link_to meal.title, meal_path(meal.id) %></div>

	  <div class="meal_right">
		<img src="/images/closed.png" title="open" alt="open" class="openMeal" /><br>
		<img src="/images/compass.png" title="Map" alt="Location" class="hoverMap" />
		<div id="map"></div>
	  </div>
	  <div class="clear"></div>
	  <span class="meal_info_right">		
      
		 <% if meal.vegetarien %>
		   <%= image_tag getCategorieImageName(0), :alt => "veggie", :title => "veggie" %>
		 <% end %>
		 <% if meal.organic %>
		   <%= image_tag getCategorieImageName(1), :alt => "organic", :title => "organic" %>
		 <% end %>
		 <% if meal.kosher %>
		   <%= image_tag getCategorieImageName(2), :alt => "kosher", :title => "hosher" %>
		 <% end %>
		 <% if meal.asian %>
		   <%= image_tag getCategorieImageName(3), :alt => "asian", :title => "asian" %>
		 <% end %>
		 <% if meal.lactose_free %>
		   <%= image_tag getCategorieImageName(4), :alt => "lactose free", :title => "lactose free" %>
		 <% end %>
		 <% if meal.gluten_free %>
		   <%= image_tag getCategorieImageName(5), :alt => "gluten", :title => "gluten" %>
		 <% end %>
		 <% if meal.halal %>
		   <%= image_tag getCategorieImageName(6), :alt => "halal", :title => "halal" %>
		 <% end %>
		 <% if meal.hot %>
			<%= image_tag getCategorieImageName(7), :alt => "hot", :title => "hot" %>
		 <% end %>
		 <% if meal.veryhot %>
			<%= image_tag getCategorieImageName(8), :alt => "veryhot", :title => "veryhot" %>
		 <% end %>
     </span>
     <span class="float_right space_right space_bottom">
       <%= link_to image_tag("edit_meal.png", :title => "edit"), edit_meal_path(meal.id) if current_user && current_user.id == meal.user_id %>
     </span>
   

      <div class="meal_info"><%=l meal.time, :format => :short %> - <%= meal.short_time %><br/>
      <p><%= meal.slots %><b>Guests</b></p>				
				<% if @rating.count > 0 %>
				<p><b>Rating:</b></p>
				  <ul>
					<% @rating.each do |rating| %>
					  <% if rating && rating.meal_id == meal.id %>
						<li><%= link_to rating.user.first_name+" "+rating.user.last_name, user_path(rating.user_id) %> <%= rating.rating %> Sterne</li>
					  <% end %>
					<% end %>
				  </ul>
				<% end %>
        <br /><br />
        <% if current_user %>
          <% if current_user.id == meal.user_id %>
			
				
			<div id="meal_info_right">
				<div id="meals_distance_stream" style="display:none">
					<div class="meal" id="meal_<%= meal.id %>">
						<input type="hidden" title="lat" value="<%= meal.lat %>" />
						<input type="hidden" title="lon" value="<%= meal.lon %>" />
					</div>
				</div>
			</div>  
		<%end%>
      <%end%>
    </div>
    </div>
   <%end%>
  <%end%>
  <% if mdisplay == 0 %>
    <h2>No formerly Meals!</h2>
  <% end %>
</div>
<% end %>

app/views/users/_upper_user_information.erb
<div id="upper_user_information" style="margin-left:77%;width:200px">
  <table>
  <tr>
  <td style="text-align:right">
  <% cache do %>
    <%= link_to image_tag(get_medium_avatar_url(user), :id => "upper_profile_avatar"), user_path(user) %>
  <% end %>
  
  </td>
  <td style="width:100px;color:white; font-size:12px">
  <% unless current_user == user %>
    <% if is_following(current_user, user) %>
      <p>
        <%= link_to image_tag("unfollow.png", :border=>0),
          get_following(:user => user), :method => :delete, :id => "remove_followed" %>
      </p>
    <% else %>
      <%if current_user %>
        <p>
          <%= link_to image_tag("follow.png", :border=>0),
            fellowships_path(:follower_id => user), :method => :post %>
        </p>
      <%end%>
    <% end %>
  <% end %>
  <% if user_signed_in? %>
    <%unless user.id == current_user.id %>
      <%= link_to image_tag("send_pm.png", :border=>0), new_message_path(:receiver => user.id), :id=>"send_message_button" %>
    <%end%>
  <% end %>

  <h4 id="following_sensor">is following:</h4>
  <div id="profile_follows">
    
  </div>

  <h4 id="followed_sensor">is followed by:</h4>
  <div id="profile_followers">
    
  </div>
  <h4><%= user.meal_counter %> Meals</h4>
  </td>
  </tr>
  </table>
</div>

app/views/users/_user_information.html.erb
<div id="user_information">
  <%= link_to image_tag(get_medium_avatar_url(user), :id => "profile_avatar"), user_path(user) %>

  <% unless current_user == user %>
    <% if is_following(current_user, user) %>
      <p>
        <%= link_to image_tag("unfollow.png", :border=>0),
          get_following(:user => user), :method => :delete, :id => "remove_followed" %>
      </p>
    <% else %>
      <%if current_user %>
        <p>
          <%= link_to image_tag("follow.png", :border=>0),
            fellowships_path(:follower_id => user), :method => :post %>
        </p>
      <%end%>
    <% end %>
  <% end %>
  <% if user_signed_in? %>
    <%unless user.id == current_user.id %>
      <%= link_to image_tag("send_pm.png", :border=>0), new_message_path(:receiver => user.id), :id=>"send_message_button" %>
    <%end%>
  <% end %>

  <h4>is following</h4>
  <div id="profile_follows">
    <% for fellowship in user.fellowships %>
    <p>
      <a href="<%= user_path(fellowship.follower.id.to_s) %>" title="<%= fellowship.follower.first_name %>" class="float_left" >
      <%= image_tag get_thumb_avatar_url(fellowship.follower), :size => "50x50", :alt => fellowship.follower.first_name %></a>
    </p>
    <% end %>
    <div class="clr"></div>
  </div>

  <h4>is followed by</h4>
  <div id="profile_followers">
    <% for user in user.inverse_followers %>
    <p>
      <a href="<%= user_path(user.id.to_s) %>" title="<%= user.first_name %>" class="float_left" >
      <%= image_tag get_thumb_avatar_url(user), :size => "50x50", :alt => user.first_name %></a>
    </p>
    <% end %>
		<br />
    <h4>Legende</h4>
    <%= image_tag 'icon_veggie.png', :alt => "veggie", :title => "veggie" %>Vegetarian<br />
    <%= image_tag 'icon_organic.png', :alt => "organic", :title => "organic" %>Organic<br />
    <%= image_tag 'icon_kosher.png', :alt => "kosher", :title => "kosher" %>Kosher<br />
    <%= image_tag 'icon_halal.png', :alt => "halal", :title => "halal" %>Halal<br />
    <%= image_tag 'icon_asian.png', :alt => "asian", :title => "asian" %>Asian<br />
    <%= image_tag 'icon_gluten-free.png', :alt => "gluten free", :title => "gluten free" %>Gluten Free<br />
    <%= image_tag 'icon_lactose-free.png', :alt => "lactose free", :title => "lactose free" %>Lactose Free<br />
    <%= image_tag 'icon_hot.png', :alt => "hot", :title => "hot" %>Hot<br />
    <%= image_tag 'icon_veryhot.png', :alt => "veryhot", :title => "veryhot" %>Verry Hot<br />
    

    <div class="clear"></div>
  </div>
</div>

app/views/users/info.html.erb
<% if current_user %>
  <%= render "upper_user_information", :user => current_user %>
<% end %>
  
<div id="main_header">
  <h3><%= @user.first_name %> <%= @user.last_name %>'s Profile</h3>
  <%= render 'layouts/menu', :user => @user %>
</div>

<div id="main_body">
  <%= render "user_information", :user => @user %>
  <%= @user.info_field %>
  <div class="clear"></div>
</div>

app/views/users/show.html.erb
<% if current_user %>
  <%= render "users/upper_user_information", :user => current_user %>
<% end %>

<div id="main_header">
  <h3><%= @user.first_name %> <%= @user.last_name %>'s Profile</h3>
  <%= render 'layouts/menu', :user => @user %>
</div>

<div id="main_body">
  <%= render "user_information", :user => @user %>
  <%= render "provided_meals", :meals => @meals %>

  <div class="clear"></div>
</div>