config/routes.rb
FoodCorp::Application.routes.draw do

  get "locations/new"

  resources :comments
	
  resources :meal_arrangements
   
  resources :ratings
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
                                       :registrations => "registrations" }

  resources :users do
    resources :locations
    match 'info' => :info
  end

  resources :fellowships
  
  resources :meals
    match 'recipes' => 'Meals#recipes', :as => 'recipes'
    match 'own_dated_meal' => 'Meals#own_dated_meal', :as => 'dates'
    match 'meals/:id/:status' => 'Meals#show', :as => 'meal_arrangement_status'
    match 'meals/create_comment' => 'Meals#create_comment', :as => 'create_commit'
  
  controller :meals do
  end

  controller :messages do
    match 'messages/in' => :inbox
    match 'messages/out' => :outbox
  end
  resources :messages

  controller :pages do
     match 'about' => :about
     match 'imprint' => :imprint
     match 'terms' => :terms
     match 'tour' => :tour
  end

  controller :ajax do
     match 'ajax/calendar' => :calendar
     match 'ajax/updatemap' => :update_map
     match 'ajax/following' => :following
     match 'ajax/followed' => :followed
  end

  root :to => "meals#index"

end

app/models/meal.rb
class Meal < ActiveRecord::Base
  
  acts_as_commentable

  attr_accessible :title, :description, :time, :deadline, :lon, :lat,
                  :country, :city, :zip_code, :street, :slots, :street_number,
		          :vegetarien, :organic, :kosher, :asian, :gluten_free, 
		          :lactose_free, :diabetics, :hot, :veryhot, :halal, :eat_in, 
		          :take_away, :got_point, :times, :deadline_time

  validates :title, :presence => true
  validates :description, :presence => true
  validates :time, :presence => true
  validates :deadline, :presence => true
  /validates :lon, :presence => true
  validates :lat, :presence => true/
  validates :slots, :presence => true
  
  belongs_to :user
  has_many :meal_arrangements
  has_many :comments
  has_many :rating

  geocoded_by :address, :latitude  => :lat, :longitude => :lon
  reverse_geocoded_by :lat, :lon
	
  def check_time
    if time.present? && times.present?
      time + (times.strftime('%H').to_i).hours - 2.hours + (times.strftime('%M').to_i).minutes
    else
      "unbekannt"
    end
  end
  

  def check_time
    if time.present? && times.present?
      time + (times.strftime('%H').to_i).hours - 3.hours + (times.strftime('%M').to_i).minutes
    end
  end
  
  def short_time
    if times.present?
      times.strftime('%H:%M')
    end
  end
  
  def short_deadline
    if deadline_time.present?
      deadline_time.strftime('%H:%M')
    end
  end
 / def check_deadline
    created_at.strftime('%d.%m').eql? Time.now.strftime('%d.%m')
  end/
end

app/controllers/meals_controller.rb
require 'rss/1.0'
require 'rss/2.0'

class MealsController < ApplicationController

  before_filter :check_login, :only=> [:new, :create, :update, :edit, :destroy]
#  before_filter :check_time, :only=> [:create, :update]
  before_filter :get_meal, :only=> [:edit, :update]
  
  def index
   @coords = request.location
   t = Time.now
   dateToday = Date.new(t.year, t.month, t.day).to_s
   @user_meals = Meal.find(:all, :conditions => ["user_id = ? AND time >=" << dateToday, current_user.id]) if current_user

   @meals = Meal.find(:all, :order => "time DESC") 


   @storred_search_location = cookies[:storred_search_location]
   @storred_search_radius = cookies[:storred_search_radius]
   
   if current_user && current_user.location
     @location = current_user.location
   else
     @location = nil
   end
  end

  def new
    @user = current_user
    @meal = Meal.new
  end

  def show
    @meal = Meal.find(params[:id])
    @meal_arrangement = MealArrangement.where(:meal_id => params[:id], :user_id => current_user.id).first if current_user
    @user = User.find( @meal.user_id )
    @rating = Rating.where(:meal_id => params[:id], :user_id => current_user.id).first if current_user
  end

  def create
    @meal = Meal.new(params[:meal])
    @meal.user_id = current_user.id
    
    if @meal.save
			@meal.user.meal_counter += 1
			@meal.user.save
			
      redirect_to meal_path(@meal.id), :notice => I18n.t('meal.create_success')
    else
      redirect_to new_meal_path,  :alert => I18n.t('meal.create_fail')
    end
  end

  def edit
  end

  def update
    if @meal.update_attributes(params[:meal])
      redirect_to meal_path(@meal.id), :notice => I18n.t('meal.create_success')
    else
      redirect_to edit_meal_path(@meal.id),  :alert => I18n.t('meal.create_fail')
    end
  end

  def destroy
  end

  def create_comment
    meal = Meal.find(params[:meal_id])
    comment = Comment.build_from(meal, current_user.id, params[:body] )
    comment.save
    redirect_to :back
  end
  
  def recipes
    @recipes_array = []
    rss_recipes = RSS::Parser.parse('http://www.recipetips.com/cooking-feed/recipes/easy-dinners.xml', false)
    
    for i in 0...rss_recipes.items.count do
      recipe = []
      
      recipe << rss_recipes.items[i].title
      
      description = rss_recipes.items[i].description
      num = description.index '.'
      recipe << description[0..num]
      
      photoStart = description.index 'src=\''
      photoEnd = description.index '\'', (photoStart+6)
      recipe << description[(photoStart+5)...photoEnd]
      
      recipe << rss_recipes.items[i].link.to_s
      
      @recipes_array << recipe
    end
  end
  
  def own_dated_meal
  @meals = Meal.joins(:meal_arrangements)
  @meal_arrangement = MealArrangement.where(:user_id => current_user.id) if current_user
  @user = User.joins(:meals => :meal_arrangements)
  end
  
  protected
  def check_login
    unless current_user
      flash[:alert] = I18n.t('application.access_denied')
      redirect_to root_path
    end
  end

  

  def get_meal
    @meal = Meal.where(:id => params[:id], :user_id => current_user.id).first
  end
  
  def get_user
    @user = User.find(params[:user_id])
  end
end

app/helpers/meals_helper.rb
module MealsHelper

  def button_request(args)
    if MealArrangement.find(:all, :conditions => { :user_id => args[:user_id] , :meal_id => args[:meal_id] }).count > 0
     return false;
    else
     return true;
    end
  end

  def user_name(args)
    firstname = User.find(args[:id]).first_name
    lastname = User.find(args[:id]).last_name
    name = firstname + " " + lastname
    return name
  end
  
  def getCategorieImageName(arg)
    array = ["icon_veggie.png", "icon_organic.png", "icon_kosher.png", "icon_asian.png", "icon_lactose-free.png", "icon_gluten-free.png", "icon_halal.png", "icon_hot.png", "icon_veryhot.png"]
    array[arg]
  end
  
  def rating_button_request(args)
   if Rating.find(:all, :conditions => { :user_id => args[:user_id] , :meal_id => args[:meal_id] }).count > 0
    return false;
   else
    return true;
   end
  end
  
  def get_number_of_guests meal_arrangments
    if meal_arrangments.empty?
      'no users have ordered this meal yet.'
    else
      num = 0
      meal_arrangments.each do |arrang|
        if arrang.acceptance
          num += 1
        end
      end
      num.to_s << ' guests are invited.'
    end
  end
end

app/views/meals/_current_meals.html.erb
<div class ="meal_schow_index" > 
   <% meals.each do |meal|%>
   
    <% if @storred_search_location.present? || params[:date].present? %>
     <% if meal.city == @storred_search_location || meal.time.to_s == params[:date] %>
       <div class ="each_meal_index" >
        <div class="meal_title"><%= link_to meal.title, meal_path(meal.id) %></div>
        <%= meal.zip_code %> <%= meal.city %> at
        <%= link_to meal.user.first_name << 's', user_path(meal.user_id) %>
		<div class="meal_icon">
			<% if meal.vegetarien %>
			<%= image_tag 'icon_veggie.png', :alt => "veggie", :title => "veggie" %>
			<% end %>
			<% if meal.organic %>
			<%= image_tag 'icon_organic.png', :alt => "organic", :title => "organic" %>
			<% end %>
			<% if meal.kosher %>
			<%= image_tag 'icon_kosher.png', :alt => "kosher", :title => "hosher" %>
			<% end %>
			<% if meal.asian %>
			<%= image_tag 'icon_asian.png', :alt => "asian", :title => "asian" %>
			<% end %>
			<% if meal.gluten_free %>
			<%= image_tag 'icon_gluten.png', :alt => "gluten", :title => "gluten" %>
			<% end %>
			<% if meal.lactose_free %>
			<%= image_tag 'icon_lactose-free.png', :alt => "lactose free", :title => "lactose free" %>
			<% end %>
			<% if meal.diabetics %>
			<%= image_tag 'icon_halal.png', :alt => "halal", :title => "halal" %>
			<% end %>
			<% if meal.hot %>
			<%= image_tag 'icon_hot.png', :alt => "hot", :title => "hot" %>
			<% end %>
			<% if meal.veryhot %>
			<%= image_tag 'icon_veryhot.png', :alt => "very hot", :title => "very hot" %>
			<% end %>
		</div>
  
    <%= l meal.time, :format => :short %><br />
    
    </div>
    
	  <% end %>
    <% else %>
     <% if meal.check_time > Time.now %>
      <div class ="each_meal_index" >
        <div class="meal_title"><%= link_to meal.title, meal_path(meal.id) %></div>
        <%= meal.zip_code %> <%=meal.city %> at
        <%= link_to meal.user.first_name, user_path(meal.user_id) %>      
		<div class="meal_icon">
			<% if meal.vegetarien %>
			<%= image_tag 'icon_veggie.png', :alt => "veggie", :title => "veggie" %>
			<% end %>
			<% if meal.organic %>
			<%= image_tag 'icon_organic.png', :alt => "organic", :title => "organic" %>
			<% end %>
			<% if meal.kosher %>
			<%= image_tag 'icon_kosher.png', :alt => "kosher", :title => "hosher" %>
			<% end %>
			<% if meal.asian %>
			<%= image_tag 'icon_asian.png', :alt => "asian", :title => "asian" %>
			<% end %>
			<% if meal.gluten_free %>
			<%= image_tag 'icon_gluten.png', :alt => "gluten", :title => "gluten" %>
			<% end %>
			<% if meal.lactose_free %>
			<%= image_tag 'icon_lactose-free.png', :alt => "lactose free", :title => "lactose free" %>
			<% end %>
			<% if meal.diabetics %>
			<%= image_tag 'icon_halal.png', :alt => "halal", :title => "halal" %>
			<% end %>
			<% if meal.hot %>
			<%= image_tag 'icon_hot.png', :alt => "hot", :title => "hot" %>
			<% end %>
			<% if meal.veryhot %>
			<%= image_tag 'icon_veryhot.png', :alt => "very hot", :title => "very hot" %>
			<% end %>
		</div>
  
    <%= l meal.time, :format => :short %><br />
    
    </div>
     <% else %>
         <div class ="each_meal_index" >
        <div class="formerly_meal_title"><%= link_to meal.title, meal_path(meal.id) %></div>
        <%= meal.zip_code %> <%=meal.city %> at
        <%= link_to meal.user.first_name, user_path(meal.user_id) %>      
		<div class="meal_icon">
			<% if meal.vegetarien %>
			<%= image_tag 'icon_veggie.png', :alt => "veggie", :title => "veggie" %>
			<% end %>
			<% if meal.organic %>
			<%= image_tag 'icon_organic.png', :alt => "organic", :title => "organic" %>
			<% end %>
			<% if meal.kosher %>
			<%= image_tag 'icon_kosher.png', :alt => "kosher", :title => "hosher" %>
			<% end %>
			<% if meal.asian %>
			<%= image_tag 'icon_asian.png', :alt => "asian", :title => "asian" %>
			<% end %>
			<% if meal.gluten_free %>
			<%= image_tag 'icon_gluten.png', :alt => "gluten", :title => "gluten" %>
			<% end %>
			<% if meal.lactose_free %>
			<%= image_tag 'icon_lactose-free.png', :alt => "lactose free", :title => "lactose free" %>
			<% end %>
			<% if meal.diabetics %>
			<%= image_tag 'icon_halal.png', :alt => "halal", :title => "halal" %>
			<% end %>
			<% if meal.hot %>
			<%= image_tag 'icon_hot.png', :alt => "hot", :title => "hot" %>
			<% end %>
			<% if meal.veryhot %>
			<%= image_tag 'icon_veryhot.png', :alt => "very hot", :title => "very hot" %>
			<% end %>
		</div>
  
    <%= l meal.time, :format => :short %><br />
    
    </div>
     <% end %>
    <% end %>
    <% end %>
</div>

app/views/meals/_map_legend.html.erb
<div style="font-size:10px">
<br />
	<p>Legend:</p><br />
	<p><img width="10%" height="10%" src="http://www.google.com/intl/en_us/mapfiles/ms/micons/blue-dot.png"></p>
	<p>Blue Marker means that autolocation is on and auto-update for adresse is off</p>
	<br />
	<p><img width="10%" height="10%" src="http://www.google.com/intl/en_us/mapfiles/ms/micons/red-dot.png"></p>
	<p>Red Marker means that autolocation off on and auto-update for adresse is on</p>
</div>

app/views/meals/_meal_and_current_user_location_form.html.erb
<% # unfortunalty this partial di not work due to @form_tag, that is a nil Class, no idea why %>

<% if current_user.location %>
	<% if current_user.location.activate %>
		<%= hidden_field_tag "current_user_locations", "y" %>
		<%= @form_tag.text_field :street_number, :value => current_user.location.street_number, :placeholder => "Street Number" %><br />

		<div class="Adress">
			<%= @form_tag.text_field :street, :value => current_user.location.street, :placeholder => "Street" %><br />
			<%= @form_tag.text_field :zip_code, :value => current_user.location.zip_code, :placeholder => "Zip Code" %><br />
			<%= @form_tag.text_field :city, :value => current_user.location.city, :placeholder => "City" %><br />
			<%= @form_tag.text_field :country, :value => current_user.location.country, :placeholder => "Country" %><br />
		</div>
	<% else %>
		<%= hidden_field_tag "current_user_locations", "n" %>
		<%= @form_tag.text_field :street_number, :placeholder => "Street Number" %><br />

		<div class="Adress">
			<%= @form_tag.text_field :street, :placeholder => "Street" %><br />
			<%= @form_tag.text_field :zip_code, :placeholder => "Zip Code" %><br />
			<%= @form_tag.text_field :city, :placeholder => "City" %><br />
			<%= @form_tag.text_field :country, :placeholder => "Country" %><br />
		</div>
	<% end %>
<% end %>

app/views/meals/edit.html.erb
<div id="main_header">
  <h3>Edit Meal</h3>
</div>
<div id="main_body">
  <%= render 'meal_form' %>

  <div class="clr"></div>
  <br>
</div>

app/views/meals/index.html.erb
<div id="main_header">
  <h3>Eat around your place!</h3>
</div>

<div id="main_body">

<!-- <h2><% unless user_signed_in? %>The world‘s most awesome cooking community. <%= link_to 'Take a tour!', tour_path %><% end  %></h2> -->

<% if current_user %>
	<table style="margin-left:20px; margin-top:20px">
	<td>You are in...</td>
	<td><%= image_tag("change.png", :id => 'animatecurrentUserLocationButton') %></td>
	</table>
	
	<div id="currentUserLocation">
	  
	  <% if @location %>
		<%= render 'locations/show_user_location' %>
		<%= link_to 'Edit your current positions', edit_user_location_path(current_user,@location) %>
	  <% else %>
		<%= link_to 'Use your position to create and edit your meals, click here', new_user_location_path(current_user) %>
	  <% end %>
		
	</div>
<% end %>

<% if current_user %>
    <% if current_user.location %>
		<% if current_user.location.activate %>
		  <div id="mealfind">Home location: <span id="currentLocation"></span></div>
		<% else %>
		  <div id="mealfind">Current location: <span id="currentLocation"></span></div>
		<% end %>
		
	<% else %>
		<div id="mealfind">Current location: <span id="currentLocation"></span></div>
	<% end %>
<% else %>
	<div id="mealfind">Current location: <span id="currentLocation"></span></div>
<% end %>

<%= form_tag(ajax_updatemap_path, :remote => true, :id => "address", :name => "address") do %>
  <%= text_field_tag :searchLocation, @storred_search_location, :placeholder => 'enter another location...' %>
  Radius: <%= select_tag :searchRadius, options_for_select([ 5, 10, 15, 20 ], @storred_search_radius), :class => "hoverSelect" %> km,
  <%= hidden_field_tag(:searchLat) %>
  <%= hidden_field_tag(:searchLon) %>
  Date: <%= text_field_tag :time , params[:date], :class => "datepickeronly"  %>
  <%= image_submit_tag("change.png", :id => :searchSubmit) %>
<% end %>

  <div id="home_wrapper">
    <div id="map" style="height:350px; width: 370px; margin: 0 0 10px 30px;" class="float_left"></div>
	<div id="meals_distance_stream">
	  <%= render "current_meals", :meals => @meals %>		
	</div>
    <div class="clr"></div>
  </div>

<div class="clr"></div>
</div>

app/views/meals/new.html.erb
<% if current_user %>
  <%= render "users/upper_user_information", :user => current_user %>
<% end %>

<div id="main_header">
  <h3>Create new Meal</h3>
  <%= render 'layouts/menu', :user => @user %>
</div>
<div id="main_body">
  
  <%= render 'meal_form' %><br /><br />
  
  <div class="clr"></div>
  <br>
</div>

app/views/meals/own_dated_meal.html.erb
<div class ="display_meal" >  
  <% mdisplay = 0 %>
	<% @meal_arrangement.each do |arrangement| %>
		<% if arrangement && arrangement.user_id == current_user.id %>
				<%# time_to_check = arrangement.meal.time + (arrangement.meal.times.strftime("%H").to_i).hours - 3.hours + (arrangement.meal.times.strftime("%M").to_i).minutes%>
				<% if arrangement.meal.check_time > Time.now %>

				  <% mdisplay = mdisplay +1 %>
				   <div class ="meal_info" >
						<div class="meal_title"><%= link_to arrangement.meal.title, meal_path(arrangement.meal.id) %></div>
						<%= arrangement.meal.zip_code %> <%= arrangement.meal.city %> at 
						<%# @user.meal_id do |user| %>
							<%= link_to arrangement.meal.user.first_name, user_path(arrangement.meal.user_id) %>
						<%# end %>
						<div class="meal_icon">
							<% if arrangement.meal.vegetarien %>
							<%= image_tag 'icon_veggie.png', :alt => "veggie", :title => "veggie" %>
							<% end %>
							<% if arrangement.meal.organic %>
							<%= image_tag 'icon_organic.png', :alt => "organic", :title => "organic" %>
							<% end %>
							<% if arrangement.meal.kosher %>
							<%= image_tag 'icon_kosher.png', :alt => "kosher", :title => "hosher" %>
							<% end %>
							<% if arrangement.meal.asian %>
							<%= image_tag 'icon_asian.png', :alt => "asian", :title => "asian" %>
							<% end %>
							<% if arrangement.meal.gluten_free %>
							<%= image_tag 'icon_gluten.png', :alt => "gluten", :title => "gluten" %>
							<% end %>
							<% if arrangement.meal.lactose_free %>
							<%= image_tag 'icon_lactose-free.png', :alt => "lactose free", :title => "lactose free" %>
							<% end %>
							<% if arrangement.meal.diabetics %>
							<%= image_tag 'icon_halal.png', :alt => "halal", :title => "halal" %>
							<% end %>
							<% if arrangement.meal.hot %>
							<%= image_tag 'icon_hot.png', :alt => "hot", :title => "hot" %>
							<% end %>
							<% if arrangement.meal.veryhot %>
							<%= image_tag 'icon_veryhot.png', :alt => "very hot", :title => "very hot" %>
							<% end %>
						</div>
				  
					   <%= l arrangement.meal.time, :format => :short %> - <%=  arrangement.meal.short_time %><br />
					
					   </div>
				  <% end %>
			<% end %>
  <% end %>
  <% if @meal_arrangement.count == 0 %>
	<br />
    <div class="meal_info"> No dates yet<br />
     To look for Meals click <%= link_to "here", "/" %></div>
  <% end %>
  <% if mdisplay == 0 && @meal_arrangement.count > 0 %>
    <div class="meal_info"> No current dates!<br />
     To look for Meals click <%= link_to "here", "/" %></div>
  <% end %>
</div>

app/views/meals/show.html.erb
<img src="/images/closed.png" title="open" alt="open" class="openMeal" />
<div id="main_header">
  <h3>Eat at <%= link_to @user.first_name << " " << @user.last_name << 's Place', user_path(@user.id) %></h3>
</div>

<div id="main_body">
	<% if @meal.present? %>
		<%# time_to_check = @meal.time + (@meal.times.strftime("%H").to_i).hours - 3.hours + (@meal.times.strftime("%M").to_i).minutes%>
		<% if @meal.check_time > Time.now %>
		<%= render "users/user_information", :user => @user %>
		<div id="provided_meals">
			<%= render 'users/meal_cook_guest_title', :meal => @meal, :meal_arrangement => @meal_arrangement %>
		
			<div class="display_meal">
				<div class="meal_right">
					<img src="/images/closed.png" title="open" alt="open" class="openMeal" /><br>
					<img src="/images/compass.png" title="Map" alt="Location" class="hoverMap" />
					<div id="map"></div>
				</div>
				<div class="clear"></div>
				<div class="meal_title"><%= link_to @meal.title, meal_path(@meal.id) %></div>
					<div class="meal_info">
					<div class="meal_icon">
						<% if @meal.vegetarien %>
						<%= image_tag 'icon_veggie.png', :alt => "veggie", :title => "veggie" %>
						<% end %>
						<% if @meal.organic %>
						<%= image_tag 'icon_organic.png', :alt => "organic", :title => "organic" %>
						<% end %>
						<% if @meal.kosher %>
						<%= image_tag 'icon_kosher.png', :alt => "kosher", :title => "hosher" %>
						<% end %>
						<% if @meal.asian %>
						<%= image_tag 'icon_asian.png', :alt => "asian", :title => "asian" %>
						<% end %>
						<% if @meal.gluten_free %>
						<%= image_tag 'icon_gluten.png', :alt => "gluten", :title => "gluten" %>
						<% end %>
						<% if @meal.lactose_free %>
						<%= image_tag 'icon_lactose-free.png', :alt => "lactose free", :title => "lactose free" %>
						<% end %>
						<% if @meal.diabetics %>
						<%= image_tag 'icon_halal.png', :alt => "halal", :title => "halal" %>
						<% end %>
						<% if @meal.hot %>
						<%= image_tag 'icon_hot.png', :alt => "hot", :title => "hot" %>
						<% end %>
						<% if @meal.veryhot %>
						<%= image_tag 'icon_veryhot.png', :alt => "very hot", :title => "very hot" %>
						<% end %>
					</div>
		  
					<%= @meal.time.strftime('%a %d.%m.%y') %> - <%= @meal.times.strftime('%H:%M') %><br>
					Description: <%= @meal.description %><br>
					<br>
					<% if current_user %>
            <%= render 'users/meals_eat_in_take_away', :meal => @meal %>
            <p>There is still a chance to eat for <%= @meal.slots %><b>Guests</b></p>
            <p><%= get_number_of_guests(@meal.meal_arrangements) %></p>
            <br />
            <div id="loc">
            <div class="street"><%= @meal.street %> <%= @meal.street_number%></div>
            <div class="city"><%= @meal.zip_code %> <%= @meal.city %></div>
            <div class="country"><%= @meal.country %></div>
					<% end %>
			
					<div id="meals_distance_stream" style="display:none">
						<div class="meal" id="meal_<%= @meal.id %>">
							<input type="hidden" title="lat" value="<%= @meal.lat %>" />
							<input type="hidden" title="lon" value="<%= @meal.lon %>" />
						</div>
					</div>
					<br />
					<%= render "layouts/meal_arrangement_button" %>
			
				</div>
			</div>
		</div>
		<div class="clear"></div>
		<% end %>
		
		<%# time_to_check = @meal.time + (@meal.times.strftime("%H").to_i).hours - 3.hours + (@meal.times.strftime("%M").to_i).minutes%>
		<% if @meal.check_time < Time.now %>
			<%= render "users/user_information", :user => @user %>
			<div id="provided_meals">	
				<%# render 'users/meal_cook_guest_title', :meal => @meal, :meal_arrangement => @meal_arrangement %>
		
			<div class="display_formerly_meal">
				<div class="meal_right">
					<img src="/images/closed.png" title="open" alt="open" class="openMeal" /><br>
					<img src="/images/compass.png" title="Map" alt="Location" class="hoverMap" />
					<div id="map"></div>
				</div>
				<div class="clear"></div>
				<div class="formerly_meal_title"><%= link_to @meal.title, meal_path(@meal.id) %></div>
				<div class="meal_info">
					<div class="meal_icon">
						<% if @meal.vegetarien %>
						<%= image_tag 'icon_veggie.png', :alt => "veggie", :title => "veggie" %>
						<% end %>
						<% if @meal.organic %>
						<%= image_tag 'icon_organic.png', :alt => "organic", :title => "organic" %>
						<% end %>
						<% if @meal.kosher %>
						<%= image_tag 'icon_kosher.png', :alt => "kosher", :title => "hosher" %>
						<% end %>
						<% if @meal.asian %>
						<%= image_tag 'icon_asian.png', :alt => "asian", :title => "asian" %>
						<% end %>
						<% if @meal.gluten_free %>
						<%= image_tag 'icon_gluten.png', :alt => "gluten", :title => "gluten" %>
						<% end %>
						<% if @meal.lactose_free %>
						<%= image_tag 'icon_lactose-free.png', :alt => "lactose free", :title => "lactose free" %>
						<% end %>
						<% if @meal.diabetics %>
						<%= image_tag 'icon_halal.png', :alt => "halal", :title => "halal" %>
						<% end %>
						<% if @meal.hot %>
						<%= image_tag 'icon_hot.png', :alt => "hot", :title => "hot" %>
						<% end %>
						<% if @meal.veryhot %>
						<%= image_tag 'icon_veryhot.png', :alt => "very hot", :title => "very hot" %>
						<% end %>
					</div>
		  
					<%= @meal.time.strftime('%a %d.%m.%y') %> - <%= @meal.times.strftime('%H:%M') %><br>
					Description: <%= @meal.description %><br>
					<br>
					<% if current_user %>
            <%= render 'users/meals_eat_in_take_away', :meal => @meal %>
            <p>There is still a chance to eat for <%= @meal.slots %><b>Guests</b></p>
            <p><%= get_number_of_guests(@meal.meal_arrangements) %></p>
            <br />
            <div id="loc">
            <div class="street"><%= @meal.street %> <%= @meal.street_number%></div>
            <div class="city"><%= @meal.zip_code %> <%= @meal.city %></div>
            <div class="country"><%= @meal.country %></div>
					<% end %>
			
					<div id="meals_distance_stream" style="display:none">
						<div class="meal" id="meal_<%= @meal.id %>">
							<input type="hidden" title="lat" value="<%= @meal.lat %>" />
							<input type="hidden" title="lon" value="<%= @meal.lon %>" />
						</div>
					</div>
					<br />
					<p>Comment this former meal.</p>
					<div id="comment_box">
						<% @meal.comment_threads.each do |comment| %>
							<div class="comment_avatar"><%= link_to image_tag(get_thumb_avatar_url(get_user_name(comment.user_id))), user_path(@user) %></div>
							<div class="comment">
								<%= link_to get_user_name(comment.user_id).first_name, user_path(@user) %>
								wrote on <%= l(comment.created_at, :format => :long) %>: <br>
								<%=  comment.body %><br>
							</div>
						<% end %>
						<%= render 'comments/comment_form', :meal => @meal %>
					</div>
					<%= render "layouts/rating_button", :rating => @rating %>
				</div>
			</div>
		</div>
		<div class="clear"></div>
		<% end %>
	<% else %>
		<h2>No Meals yet</h2>
	<% end %>
</div>