config/routes.rb
FoodCorp::Application.routes.draw do

  get "locations/new"

  resources :comments
	
  resources :meal_arrangements
   
  resources :ratings
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
                                       :registrations => "registrations" }

  resources :users do
    resources :locations
    match 'info' => :info
  end

  resources :fellowships
  
  resources :meals
    match 'recipes' => 'Meals#recipes', :as => 'recipes'
    match 'own_dated_meal' => 'Meals#own_dated_meal', :as => 'dates'
    match 'meals/:id/:status' => 'Meals#show', :as => 'meal_arrangement_status'
    match 'meals/create_comment' => 'Meals#create_comment', :as => 'create_commit'
  
  controller :meals do
  end

  controller :messages do
    match 'messages/in' => :inbox
    match 'messages/out' => :outbox
  end
  resources :messages

  controller :pages do
     match 'about' => :about
     match 'imprint' => :imprint
     match 'terms' => :terms
     match 'tour' => :tour
  end

  controller :ajax do
     match 'ajax/calendar' => :calendar
     match 'ajax/updatemap' => :update_map
     match 'ajax/following' => :following
     match 'ajax/followed' => :followed
  end

  root :to => "meals#index"

end

app/views/layouts/_header.html.erb
<div id="logo"><a href="/"><img src="/images/logo.png" /></a></div>
<div id="top_navigation_container">

  <ul id="topnav">
  <% if user_signed_in? %>
	<li><%= link_to("eat", dates_path, :id => "topnav_eat", :class => is_active?("nav_active")) %></li>
  <% else %>
    <li><%= link_to("eat", meals_path, :id => "topnav_eat", :class => is_active?("nav_active") )  %></li>
  <% end %>
    <li><%= link_to("register", new_user_registration_path, :id => "topnav_register", :class => is_active?("nav_active") ) unless user_signed_in? %></li>
    <li><%= link_to("cook", new_meal_path, :id => "topnav_cook", :class => is_active?("show"), :class => ("new")) if user_signed_in? %></li>
  </ul>

  <% if user_signed_in? %>
  <div id="calendar">
      <div id="calendar_container">
      </div>
      <div id="calendar_pull">
      	<img src="/images/calendar_pull.png" />
      </div>
  </div>
  <% end %>

</div>
<div class="clr"></div>

app/views/layouts/_meal_arrangement_button.html.erb
<% if current_user %>
  <% if current_user.id == @meal.user_id %>
    
    <% if @meal.meal_arrangements.length != 0 %>
		<h3>Following users have ordered your meal</h3>
		
      <% for i in 0...@meal.meal_arrangements.length %>
        <% user = @meal.meal_arrangements[i].user.first_name << ' ' << @meal.meal_arrangements[i].user.last_name %>
        <%= 'user: ' << user %>
        
        <% if @meal.meal_arrangements[i].acceptance %>
            <p>Meal order's been accepted already.</p>
        <% else %>
          <p>You can accept this order of user <%= user %></p>
          <%= render 'users/meal_arrangement_update_form', :meal_arrangement => @meal.meal_arrangements[i] %>
        <% end %>
        <p>You can delete this order of user <%= user %></p>
        <%= render 'users/meal_arrangement_delete_form', :meal_arrangement => @meal.meal_arrangements[i] %>
        <br />
      <% end %>
		
    <% end %>
    
    <p>Click button below to edit meal.</p>
    <%= link_to image_tag("edit_meal.png", :title => "edit", :id => "edit_meal"), edit_meal_path(@meal.id) %>
    
  <% else %>
    <% if button_request(:meal_id => @meal.id, :user_id => current_user.id) %>
      <% if current_user.points > 0 %>
        
			<p>When you order this meal, you may want to receive a mail notification, when meal is ready to eat?</p>
			
			<%= form_tag({:controller => "meal_arrangements", :action => "create"}, :method => "post") do %>
			  <%= hidden_field_tag 'meal_id', @meal.id %>
			  
			  <%= render 'users/mail_notifications_buttons', :on => current_user.mail_notification %>
			  <p><%= image_submit_tag("request_meal.png", :id => "request_meal") %></p>
			<% end %>
			
      <% else %>
          <p>Unfortunately you do not have got points to order this meal.</p>
          <%= image_submit_tag("no_request_meal.png", :disabled => false) %>
      <% end %>
		
    <%else%>
        
        <p>Do you want to receive mail notifications at all? This would concern your meal notififactions as well.</p>
        
        <%= form_for current_user, :method => :update do |u| %>
          <%= hidden_field_tag 'user_id', current_user.id, :value => current_user.id %>
                <%= render 'users/mail_notifications_buttons', :on => current_user.mail_notification %>
                <%= image_submit_tag "update_mail_notification.png" %>
        <% end %>
        
        <% if @meal_arrangement && !@meal_arrangement.acceptance %>
          <p>Delete your order of this meal? Click on button below</p>
          <%= form_tag(meal_arrangement_path(@meal_arrangement.id), :method => "delete") do %>
            <%= image_submit_tag("delete_meal_request.png", :id => "delete_meal_request") %>
          <%end%>
        <% end %>
        
    <%end%>
  <% end %>
    
<% else %>
  <p>You have to log in in order to make an order of this meal.</p>
  <%= link_to image_tag("login_to_eat.png", :title => "login to eat"), user_session_path %>
<% end %>

app/views/layouts/_menu.html.erb
<div id="tabnav">
  <ul>
    <li><%= link_to "meals", user_path(user.id), :class => is_active?("show"), :id => "meals/" << current_user.id.to_s if current_user %></li>
    <% if current_user %>
      <% if current_user.id == user.id %>
        <li><%= link_to "+", new_meal_path, :class => is_active?("new"), :id => "tab_new_meal" %></li>
      <%end%>
    <%end%>
    <li><%= link_to "info", user_info_path(user.id), :class => is_active?("info") %></li>
	<li><%= link_to "recipes", recipes_path, :class => is_active?("recipes") %></li>
  </ul>
</div>

app/views/layouts/_rating_button.html.erb
<% if current_user %>
    <% if current_user && current_user.id != @meal.user_id %>
	  <% unless rating %>
      <% if rating_button_request(:meal_id => @meal.id, :user_id => current_user.id) %>
			
			<p>You can rate the meal with 1 to 5 stars.</p>
			
			<%= form_tag({:controller => "ratings", :action => "create"}, :method => "post") do %>
			  <%= hidden_field_tag 'meal_id', @meal.id %>
			  
			  <%= select(:rating, :rating, [['1 Stern', 1], ['2 Sterne', 2], ['3 Sterne', 3], ['4 Sterne', 4], ['5 Sterne', 5]]) %>
			  <p><%= image_submit_tag("rate_meal.png") %></p>
			<% end %>
      <% end %>
      <% end %>
      <% if rating && rating.user_id == current_user.id && rating.meal_id == @meal.id %>
	      Bewertung von <%= rating.user.first_name %> mit: <%= @rating.rating %> Sternen.	      
      <% end %>  
    <% end %>  
<% else %>
  <p>You have to log in in order to make an order of this meal.</p>
  <%= link_to image_tag("login_to_eat.png", :title => "login to eat"), user_session_path %>
<% end %>

app/views/layouts/_registration.html.erb
<% if !user_signed_in? %>
  <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook), :id => "fb_sign_in" %>
  <br/>
  <%= form_for("user", :url => user_session_path) do |f| %>
    <%= f.text_field :email %>
    <%= f.password_field :password %>
    <%= f.check_box :remember_me %>
    <%= f.label :remember_me %>
    <%= f.submit 'Sign in' %>
    <%= link_to "Forgot your password?", new_password_path('user') %>
    <%= link_to('Register', new_user_registration_path)  %>
  <% end %>
<% end %>
<div class="clear"></div>

app/views/layouts/_user_info.html.erb
<div id="login" class="" id="user_info">
    <% if user_signed_in? %>
	<table>
	<tr>
	<td>
       <p><%= link_to(current_user.first_name + " " + current_user.last_name, user_path(current_user.id) )%><br>
	   <%= link_to('personal Messages', messages_path, :id => "personal Messages")%><br>
	   <%= current_user.points %> - <%= link_to('edit Profile', edit_user_registration_path) %> -
	   <%= link_to('Logout', destroy_user_session_path) %></p>
	 </td>
	   <%# link_to image_tag(get_thumb_avatar_url(current_user), :title => "my Profile"), user_path(current_user.id), :id => "user_info_picture" %>
	 </tr>
	</table> 
    <% else %>
      
      <p><%= link_to "Login", "#", :id => "signup_form_animate" %> or
		 <%= link_to "Login with Facebook", user_omniauth_authorize_path(:facebook), :id => "fb_sign_in" %>
      
      <div style="margin-top:10px; float:right" class="fb-like" data-href="http://dinnercollective.com/" data-send="true" data-layout="button_count" data-width="100" data-show-faces="true" data-colorscheme="dark"></div>
      
      </p>
      <div id="signup_form">
         <%= form_for("user", :url => user_session_path) do |f| %>
           <%= f.submit 'Sign in', :class =>"float_right" %><br />
           <%= f.text_field :email, :placeholder => "e-mail" %><br />
           <%= f.password_field :password, :placeholder => "password" %><br />
         <% end %>
      </div>
    <% end %>
 </div>

app/views/layouts/_user_information.html.erb
<div id="user_information">
  <div id="black" ></div>
  <%= image_tag get_medium_avatar_url(@user), :id => "profile_avatar" %>

  <h3 id="profile_name"><%= @user.first_name %> <%= @user.last_name %></h3>
  <div id="user_info">
    <% @user.info_field %>	
  </div>

  <% unless current_user == @user %>
    <% if is_following(current_user, @user) %>
      <p>
        <%= link_to image_tag("unfollow.png", :border=>0),
          get_following(:user => @user), :method => :delete, :id => "remove_followed" %>
      </p>
    <% else %>
      <%if current_user %>
        <p>
          <%= link_to image_tag("follow.png", :border=>0),
            fellowships_path(:follower_id => @user), :method => :post %>
        </p>
      <%end%>
    <% end %>
  <% end %>
  <% if user_signed_in? %>
    <%unless @user.id == current_user.id %>
      <%= link_to "Send "+@user.first_name+" a PM", new_message_path(:receiver => @user.id) %>
    <%end%>
  <% end %>
      
  <h3>is following</h3>
  <div id="profile_follows">
    <% for fellowship in @user.fellowships %>
    <p>
      <a href="<%= user_path(fellowship.follower.id.to_s) %>" title="<%= fellowship.follower.first_name %>" class="float_left" >
      <%= image_tag get_thumb_avatar_url(fellowship.follower), :size => "50x50", :alt => fellowship.follower.first_name %></a>
    </p>
    <% end %>
    <div class="clr"></div>
  </div>

  <h3>is followed by</h3>
  <div id="profile_followers">
    <% for user in @user.inverse_followers %>
    <p>
      <a href="<%= user_path(user.id.to_s) %>" title="<%= user.first_name %>" class="float_left" >
      <%= image_tag get_thumb_avatar_url(user), :size => "50x50", :alt => user.first_name %></a>
    </p>
    <% end %>
    <div class="clr"></div>
  </div>
</div>

app/views/layouts/ajax.html.erb
<%= yield %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= I18n.t 'application.title'  %> </title>
  <%= stylesheet_link_tag :all %>
  <%= csrf_meta_tag %>
  <meta name="updated_at" content="26.10.2012" />
 <script src="https://www.google.com/jsapi?key=ABQIAAAAbJBurE6AcWFl0i1KGIO4ThS_YDogaUe9kD9y-xH7PTIONHSzWRTfCAu0UNLWzcsKyeoVU06m6-q6uw" type="text/javascript"></script>

  <script language="Javascript" type="text/javascript">
    //<![CDATA[
      google.load("maps", "true");
    //]]>
  </script>
  <%= javascript_include_tag "jquery.min", "jquery-ui.min", "rails", "jquery.maps", "jquery.cookie", "jquery.timepicker", "jquery.hoverintent", "geo", "foodcorp", "http://www.geoplugin.net/javascript.gp", "jquery-autocomplete/lib/jquery.bgiframe.min", "jquery-autocomplete/lib/jquery.dimensions", "jquery-autocomplete/jquery.autocomplete" %>
</head>
<body>
  <!-- FB Like Button -->
  <script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/de_DE/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

  <div style=''>
  <%= render 'layouts/user_info' %>
  </div>
  <div id="wrapper">
  <%= render 'layouts/header' %>
  <div id="notifications">
    <p class="notice" align="center"><%= notice %></p>
    <p class="alert" align="center"><%= alert %></p>
  </div>
  <div id="main">
    <%= yield %>
  </div>
  <div id="footer">
  	<%= link_to "About", about_path %> -
	<%= link_to "Imprint", imprint_path %> -
	<%= link_to "Terms of service", terms_path %>
  </div>
  </div>
</body>
</html>